##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.8.0-B50] date: [Thu May 14 14:55:41 CST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
# Modified for:
#   1. Windows + MSYS2 + GNU Make
#   2. Linux + GNU Make
#   3. Windows environment variables GCC and FLASH_RTT
#   4. SEGGER J-Link Commander / RTT Client
#
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = channel1_device


ALLCSRC =
ALLINC =
include device/device.mk
include ARM_SEGGER_RTT/segger_rtt.mk
######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/spi.c \
Core/Src/tim.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Core/Src/system_stm32f4xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
LWIP/Target/ethernetif.c \
LWIP/App/lwip.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/auth.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/ccp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/chap_ms.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/chap-md5.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/chap-new.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/demand.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/eap.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/eui64.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/fsm.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/ipcp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/ipv6cp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/lcp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/magic.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/mppe.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/multilink.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/ppp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppapi.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppcrypt.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppoe.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppol2tp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppos.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/upap.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/utils.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/vj.c \
Middlewares/Third_Party/LwIP/src/netif/bridgeif.c \
Middlewares/Third_Party/LwIP/src/netif/bridgeif_fdb.c \
Middlewares/Third_Party/LwIP/src/netif/ethernet.c \
Middlewares/Third_Party/LwIP/src/netif/lowpan6.c \
Middlewares/Third_Party/LwIP/src/netif/lowpan6_ble.c \
Middlewares/Third_Party/LwIP/src/netif/lowpan6_common.c \
Middlewares/Third_Party/LwIP/src/netif/slipif.c \
Middlewares/Third_Party/LwIP/src/netif/zepif.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/ecp.c \
Middlewares/Third_Party/LwIP/src/api/api_lib.c \
Middlewares/Third_Party/LwIP/src/api/api_msg.c \
Middlewares/Third_Party/LwIP/src/api/err.c \
Middlewares/Third_Party/LwIP/src/api/if_api.c \
Middlewares/Third_Party/LwIP/src/api/netbuf.c \
Middlewares/Third_Party/LwIP/src/api/netdb.c \
Middlewares/Third_Party/LwIP/src/api/netifapi.c \
Middlewares/Third_Party/LwIP/src/api/sockets.c \
Middlewares/Third_Party/LwIP/src/api/tcpip.c \
Middlewares/Third_Party/LwIP/src/core/altcp.c \
Middlewares/Third_Party/LwIP/src/core/altcp_alloc.c \
Middlewares/Third_Party/LwIP/src/core/altcp_tcp.c \
Middlewares/Third_Party/LwIP/src/core/def.c \
Middlewares/Third_Party/LwIP/src/core/dns.c \
Middlewares/Third_Party/LwIP/src/core/inet_chksum.c \
Middlewares/Third_Party/LwIP/src/core/init.c \
Middlewares/Third_Party/LwIP/src/core/ip.c \
Middlewares/Third_Party/LwIP/src/core/mem.c \
Middlewares/Third_Party/LwIP/src/core/memp.c \
Middlewares/Third_Party/LwIP/src/core/netif.c \
Middlewares/Third_Party/LwIP/src/core/pbuf.c \
Middlewares/Third_Party/LwIP/src/core/raw.c \
Middlewares/Third_Party/LwIP/src/core/stats.c \
Middlewares/Third_Party/LwIP/src/core/sys.c \
Middlewares/Third_Party/LwIP/src/core/tcp.c \
Middlewares/Third_Party/LwIP/src/core/tcp_in.c \
Middlewares/Third_Party/LwIP/src/core/tcp_out.c \
Middlewares/Third_Party/LwIP/src/core/timeouts.c \
Middlewares/Third_Party/LwIP/src/core/udp.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/autoip.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/dhcp.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/etharp.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/icmp.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/igmp.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/ip4.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_addr.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/dhcp6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/ethip6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/icmp6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/inet6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/ip6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_addr.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_frag.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/mld6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/nd6.c \
Middlewares/Third_Party/LwIP/src/apps/mqtt/mqtt.c

C_SOURCES += $(ALLCSRC)
# ASM sources
ASM_SOURCES =  \
startup_stm32f427xx.s

# ASMM sources
ASMM_SOURCES =


#######################################
# host and external tools
#######################################
# Windows/MSYS2 supports the environment variables already used on this PC:
#
#   GCC       = D:\gcc\<toolchain-root>
#   FLASH_RTT = D:\J-LINK\JLink_V794
#
# GCC may point either to the toolchain root directory or directly to its
# bin directory. Backslashes are converted to forward slashes automatically.
#
# Command-line values have higher priority, for example:
#
#   make GCC_PATH=/d/gcc/toolchain/bin
#   make JLINK_ROOT=/d/J-LINK/JLink_V794 flash
#
# If no explicit path is provided, Windows also searches:
#
#   D:/gcc/*/bin/arm-none-eabi-gcc.exe
#   D:/J-LINK/JLink_V*/JLink.exe

.DEFAULT_GOAL := all

# Convert Windows backslashes to Make/MSYS-compatible forward slashes.
normalize_path = $(subst \,/,$(strip $(1)))

ifeq ($(OS),Windows_NT)
HOST_OS := windows
EXEEXT := .exe
else
HOST_OS := linux
EXEEXT :=
endif

# Optional explicit settings.
GCC_PATH ?=
GCC_ROOT ?= $(GCC)
JLINK_ROOT ?= $(FLASH_RTT)

GCC_PATH := $(call normalize_path,$(GCC_PATH))
GCC_ROOT := $(call normalize_path,$(GCC_ROOT))
JLINK_ROOT := $(call normalize_path,$(JLINK_ROOT))

ifeq ($(HOST_OS),windows)

# Resolve the ARM GCC bin directory.
ifeq ($(strip $(GCC_PATH)),)
ifneq ($(strip $(GCC_ROOT)),)
ifneq ($(wildcard $(GCC_ROOT)/arm-none-eabi-gcc.exe),)
GCC_PATH := $(GCC_ROOT)
else
GCC_PATH := $(GCC_ROOT)/bin
endif
else
AUTO_GCC_EXE := $(firstword $(wildcard D:/gcc/*/bin/arm-none-eabi-gcc.exe))
ifneq ($(strip $(AUTO_GCC_EXE)),)
GCC_PATH := $(patsubst %/arm-none-eabi-gcc.exe,%,$(AUTO_GCC_EXE))
endif
endif
endif

# Resolve the SEGGER J-Link directory.
ifeq ($(strip $(JLINK_ROOT)),)
AUTO_JLINK_EXE := $(firstword $(wildcard D:/J-LINK/JLink_V*/JLink.exe))
ifneq ($(strip $(AUTO_JLINK_EXE)),)
JLINK_ROOT := $(patsubst %/JLink.exe,%,$(AUTO_JLINK_EXE))
endif
endif

else

# Keep compatibility with the original Ubuntu toolchain location.
ifeq ($(strip $(GCC_PATH)),)
ifneq ($(wildcard /opt/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-gcc),)
GCC_PATH := /opt/gcc-arm-none-eabi-9-2020-q2-update/bin
endif
endif

endif

#######################################
# binaries
#######################################
PREFIX := arm-none-eabi-

ifeq ($(strip $(GCC_PATH)),)
CC := $(PREFIX)gcc$(EXEEXT)
AS := $(PREFIX)gcc$(EXEEXT)
CP := $(PREFIX)objcopy$(EXEEXT)
SZ := $(PREFIX)size$(EXEEXT)
else
CC := $(GCC_PATH)/$(PREFIX)gcc$(EXEEXT)
AS := $(GCC_PATH)/$(PREFIX)gcc$(EXEEXT)
CP := $(GCC_PATH)/$(PREFIX)objcopy$(EXEEXT)
SZ := $(GCC_PATH)/$(PREFIX)size$(EXEEXT)
endif

ifeq ($(strip $(JLINK_ROOT)),)
ifeq ($(HOST_OS),windows)
JLINK_EXE := JLink.exe
RTT_CLIENT_EXE := JLinkRTTClient.exe
RTT_VIEWER_EXE := JLinkRTTViewer.exe
else
JLINK_EXE := JLinkExe
RTT_CLIENT_EXE := JLinkRTTClient
RTT_VIEWER_EXE := JLinkRTTViewerExe
endif
else
ifeq ($(HOST_OS),windows)
JLINK_EXE := $(JLINK_ROOT)/JLink.exe
RTT_CLIENT_EXE := $(JLINK_ROOT)/JLinkRTTClient.exe
RTT_VIEWER_EXE := $(JLINK_ROOT)/JLinkRTTViewer.exe
else
JLINK_EXE := $(JLINK_ROOT)/JLinkExe
RTT_CLIENT_EXE := $(JLINK_ROOT)/JLinkRTTClient
RTT_VIEWER_EXE := $(JLINK_ROOT)/JLinkRTTViewerExe
endif
endif

HEX = "$(CP)" -O ihex
BIN = "$(CP)" -O binary -S


#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F427xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
Core/Inc \
Drivers/STM32F4xx_HAL_Driver/Inc \
Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
Drivers/CMSIS/Device/ST/STM32F4xx/Include \
Drivers/CMSIS/Include \
LWIP/App \
LWIP/Target \
Middlewares/Third_Party/LwIP/src/include \
Middlewares/Third_Party/LwIP/system \
Middlewares/Third_Party/LwIP/src/include/netif/ppp \
Middlewares/Third_Party/LwIP/src/include/lwip \
Middlewares/Third_Party/LwIP/src/include/lwip/apps \
Middlewares/Third_Party/LwIP/src/include/lwip/priv \
Middlewares/Third_Party/LwIP/src/include/lwip/prot \
Middlewares/Third_Party/LwIP/src/include/netif \
Middlewares/Third_Party/LwIP/src/include/compat/posix \
Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa \
Middlewares/Third_Party/LwIP/src/include/compat/posix/net \
Middlewares/Third_Party/LwIP/src/include/compat/posix/sys \
Middlewares/Third_Party/LwIP/src/include/compat/stdc \
Middlewares/Third_Party/LwIP/system/arch
C_INCLUDES += $(ALLINC)
C_INCLUDES := $(patsubst %,-I%,$(C_INCLUDES))

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F427XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
.PHONY: all clean flash erase run telnet rtt viewer info help \
        check-tools check-gcc check-binutils check-jlink check-rtt-client

all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# tool checks and diagnostics
#######################################
check-gcc:
	@if [ -x "$(CC)" ] || command -v "$(CC)" >/dev/null 2>&1; then \
		:; \
	else \
		echo "ERROR: ARM GCC was not found."; \
		echo "Resolved compiler: $(CC)"; \
		echo "Set the Windows environment variable GCC to the toolchain root,"; \
		echo "or run: make GCC_PATH=/d/path/to/toolchain/bin"; \
		exit 1; \
	fi

check-binutils:
	@if { [ -x "$(CP)" ] || command -v "$(CP)" >/dev/null 2>&1; } && \
	    { [ -x "$(SZ)" ] || command -v "$(SZ)" >/dev/null 2>&1; }; then \
		:; \
	else \
		echo "ERROR: arm-none-eabi-objcopy or arm-none-eabi-size was not found."; \
		echo "Resolved objcopy: $(CP)"; \
		echo "Resolved size:    $(SZ)"; \
		exit 1; \
	fi

check-tools: check-gcc check-binutils

check-jlink:
	@if [ -x "$(JLINK_EXE)" ] || command -v "$(JLINK_EXE)" >/dev/null 2>&1; then \
		:; \
	else \
		echo "ERROR: SEGGER J-Link Commander was not found."; \
		echo "Resolved J-Link: $(JLINK_EXE)"; \
		echo "Set FLASH_RTT or run: make JLINK_ROOT=/d/J-LINK/JLink_Vxxx"; \
		exit 1; \
	fi

check-rtt-client:
	@if [ -x "$(RTT_CLIENT_EXE)" ] || command -v "$(RTT_CLIENT_EXE)" >/dev/null 2>&1; then \
		:; \
	else \
		echo "ERROR: SEGGER J-Link RTT Client was not found."; \
		echo "Resolved RTT client: $(RTT_CLIENT_EXE)"; \
		exit 1; \
	fi

info:
	@echo "HOST_OS          = $(HOST_OS)"
	@echo "GCC environment  = $(GCC)"
	@echo "GCC_ROOT         = $(GCC_ROOT)"
	@echo "GCC_PATH         = $(GCC_PATH)"
	@echo "CC               = $(CC)"
	@echo "CP               = $(CP)"
	@echo "SZ               = $(SZ)"
	@echo "FLASH_RTT env    = $(FLASH_RTT)"
	@echo "JLINK_ROOT       = $(JLINK_ROOT)"
	@echo "JLINK_EXE        = $(JLINK_EXE)"
	@echo "RTT_CLIENT_EXE   = $(RTT_CLIENT_EXE)"
	@echo "BUILD_DIR        = $(BUILD_DIR)"
	@echo "TARGET           = $(TARGET)"

help:
	@echo "Available targets:"
	@echo "  make info        - show all resolved tool paths"
	@echo "  make check-tools - verify ARM GCC and binutils"
	@echo "  make             - build ELF, HEX and BIN"
	@echo "  make clean       - remove the build directory"
	@echo "  make flash       - build and program with J-Link"
	@echo "  make erase       - erase the MCU with J-Link"
	@echo "  make run         - start J-Link Commander and RTT Telnet server"
	@echo "  make telnet      - connect with JLinkRTTClient"
	@echo "  make viewer      - open JLinkRTTViewer"


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

# Tool checks are order-only prerequisites: they do not force recompilation.
$(OBJECTS): | check-tools

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	@"$(CC)" -c $(CFLAGS) \
		-Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) \
		$< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	@"$(AS)" -x assembler-with-cpp -c $(ASFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	@"$(AS)" -x assembler-with-cpp -c $(ASFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile | check-tools
	@"$(CC)" $(OBJECTS) $(LDFLAGS) -o $@
	@"$(SZ)" $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR) check-binutils
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR) check-binutils
	$(BIN) $< $@

$(BUILD_DIR):
	@mkdir -p $@


#######################################
# clean, programming and RTT
#######################################
JLINK_SN ?= 20722677
JLINK_DEVICE ?= STM32F427VG
JLINK_IF ?= SWD
JLINK_SPEED ?= 4000
JLINK_RUN_SPEED ?= 2400
JLINK_RTT_PORT ?= 6666

clean:
	@rm -rf $(BUILD_DIR)

flash: all check-jlink
	@echo "Uploading firmware with J-Link..."
	@"$(JLINK_EXE)" \
		-SelectEmuBySN $(JLINK_SN) \
		-Device $(JLINK_DEVICE) \
		-if $(JLINK_IF) \
		-Speed $(JLINK_SPEED) \
		-CommandFile ./flash.jlink

erase: check-jlink
	@echo "Erasing chip with J-Link..."
	@"$(JLINK_EXE)" \
		-SelectEmuBySN $(JLINK_SN) \
		-Device $(JLINK_DEVICE) \
		-if $(JLINK_IF) \
		-Speed $(JLINK_SPEED) \
		-CommandFile ./erase.jlink

run: check-jlink
	@echo "Starting J-Link Commander and RTT server on port $(JLINK_RTT_PORT)..."
	@"$(JLINK_EXE)" \
		-SelectEmuBySN $(JLINK_SN) \
		-Device $(JLINK_DEVICE) \
		-if $(JLINK_IF) \
		-Speed $(JLINK_RUN_SPEED) \
		-RTTTelnetPort $(JLINK_RTT_PORT) \
		-autoconnect 1

telnet: check-rtt-client
	@echo "Connecting to RTT server on localhost:$(JLINK_RTT_PORT)..."
	@while true; do \
		"$(RTT_CLIENT_EXE)" -RTTTelnetPort $(JLINK_RTT_PORT); \
		echo "RTT connection closed; retrying in 1 second..."; \
		sleep 1; \
	done

rtt: telnet

viewer:
	@if [ -x "$(RTT_VIEWER_EXE)" ] || command -v "$(RTT_VIEWER_EXE)" >/dev/null 2>&1; then \
		"$(RTT_VIEWER_EXE)"; \
	else \
		echo "ERROR: JLinkRTTViewer was not found: $(RTT_VIEWER_EXE)"; \
		exit 1; \
	fi


#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
